spring:
  application:
    name: spring-eureka
server:
  port: 8671
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
