spring:
  application:
    name: spring-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yclooper/spring-demo-config
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
