spring:
  application:
    name: spring-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yclooper/spring-demo-config
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"